spring.application.name=jwt-demo

#Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bpfurniture
spring.datasource.username=root
spring.datasource.password=${MY_SQL_PASSWORD}


# Hibernate Configuration
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ai calls
Ai.Server.Url="http://localhost:11434/api/generate"




# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=36000000


google.client-id=${GOOGLE_LOG_IN_ID}



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SYSTEM_GOOGLE_GMAIL}
spring.mail.password=${SYSTEM_GOOGLE_GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true