spring.application.name=jwt-demo

# H2 Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bpfurniture
spring.datasource.username=root
spring.datasource.password=1234

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# JWT Configuration
jwt.secret=thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
jwt.expiration=36000000
